### PR TITLE
[WIP] Better progress reporting

### PR DESCRIPTION
**Pull request by j2ghz**
To make the code more maintainable, I propose replacing progress carrying doubles
```
            // purely for progress reporting
            var progPercent = 0.0;
            var percentPerUser = 100 / users.Count;
```
and method signatures like
```
        private async Task SyncUserLibrary(
            User user,
            TraktUser traktUser,
            double progPercent,
            double percentPerUser,
            IProgress<double> progress,
            CancellationToken cancellationToken)
        {
```
with SplittableProgress class

Example of usage (SyncLibraryTask.Execute, removed everything except progress reporting):
```
        public async Task Execute(CancellationToken cancellationToken, IProgress<double> progress)
        {
            // purely for progress reporting
            var progPercent = 0.0;
            var percentPerUser = 100 / users.Count;
            foreach (var user in users)
            {
                await SyncUserLibrary(user, traktUser, progPercent, percentPerUser, progress, cancellationToken)
                        .ConfigureAwait(false);
                progPercent += percentPerUser;
            }
        }
```
can be replaced by:
```
        public async Task Execute(CancellationToken cancellationToken, IProgress<double> progress)
        {
            foreach (var user in users)
            {
                await SyncUserLibrary(user, traktUser, progress.Split(users.Count), cancellationToken)
                        .ConfigureAwait(false);
            }
        }
```

Input welcome on:
```
var prog = new Progress<double>();
var sProg = new SplittableProgress();

prog.Report(100);
prog.Report(100);
//Reports 100 and then 100
//Absolute reporting

sProg.Report(100);
sProg.Report(100);
//Reports 100 and then 200
//Relative (additive) reporting
```
Is it okay or will it be confusing to others?

I'm waiting for a green light before actually replacing it.

### CODE REVIEW

**Comment by LukePulverenti** [comment]
The plugin can do whatever it likes internally but that still won't affect the interface of IScheduledTask. Or are you looking to change that too?

**Comment by j2ghz** [comment]
No. I don't see any benefit to that. That's what the extensions are for, so you can receive `Progress<double> progress` from Emby and use `progress.Split(users.Count)` to get `SplittableProgress`. If there are other plugins that'd benefit from having `SplittableProgress` it could be moved to Emby.

**Comment by LukePulverenti** [comment]
I think the intended pattern of IProgress is that each method that accepts an IProgress will report it's progress in a standalone manner, without worrying about progress of the overall containing operation. 

For example, the outer scheduled task accepts an IProgress that reports back to Emby core from 0-100. Let's say there are 4 sub-operations. Each sub-operation will accept it's own IProgress that reports from 0-100. The outer operation then listens to each one and combines them all to calculate the overall progress reported, and so on and so forth.

Does this make sense? I am not saying you have to do this, it is only my suggestion. Since you are taking the time to write unit tests to validate your approach I am perfectly fine with the direction you are taking it in.

**Comment by j2ghz** [comment]
That's exactly what I mean, except:

> Each sub-operation will accept it's own IProgress that reports from 0-100.

Instead of `IProgress` it will be `ISplittableProgress`, so that people notice the difference in behaviour (see first post)

**Comment by LukePulverenti** [comment]
Ah yes ok, makes sense. thanks.

**Comment by LukePulverenti** [comment]
Do you have any knowledge of what might be going on here with multi-episode files? 
https://emby.media/community/index.php?/topic/43859-trakt-plugin-not-syncing-multi-episodes/#entry439988

Thanks !

**Pull request merged**
